FROM rust:1.82-slim-bookworm as builder
WORKDIR /app
COPY rust_lb /app
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/rust_lb .
CMD ["./rust_lb"]
