FROM rust:1.82-slim-bookworm as builder
WORKDIR /app

# Cache dependencies
COPY rust_lb/Cargo.toml rust_lb/Cargo.lock* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && \
    cargo build --release && rm -rf src

# Build actual code
COPY rust_lb/src ./src
RUN RUSTFLAGS="-C target-cpu=haswell -C link-arg=-s" cargo build --release

FROM gcr.io/distroless/cc-debian12:latest
WORKDIR /app
COPY --from=builder /app/target/release/rust_lb .
CMD ["./rust_lb"]
